# Generated by Django 5.0.2 on 2024-02-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='datatime_created',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='datatime_modified',
            new_name='datetime_modified',
        ),
    ]
