# Generated by Django 5.0.2 on 2024-03-16 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=200)),
                ('status', models.IntegerField(null=True)),
                ('track_id', models.IntegerField(null=True)),
                ('order_id', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField()),
                ('card_no', models.CharField(max_length=200, null=True)),
                ('hashed_card_no', models.CharField(max_length=200, null=True)),
                ('to_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='order.order')),
            ],
        ),
    ]
